###Регистрация пользователя
POST localhost:8081/api/auth/signup
Content-Type: application/json

{
  "username": "smirnovpa",
  "email": "123@yandex.ru",
  "name": "Смирнов Павел Антонович",
  "password": "123123"
}

###Аутентификация пользователя
POST localhost:8081/api/auth/signin
Content-Type: application/json

{
  "username": "smirnovpa",
  "password": "123123"
}